# Generated by Django 5.1.3 on 2025-03-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackaton_app', '0002_remove_mail_address_is_allowed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail_address',
            name='is_quarantined',
        ),
        migrations.AddField(
            model_name='mail',
            name='is_quarantined',
            field=models.BooleanField(default=False),
        ),
    ]
