# Generated by Django 5.1.3 on 2025-03-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackaton_app', '0003_remove_mail_address_is_quarantined_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_whitelisted', models.BooleanField(default=False)),
                ('is_blacklisted', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Mail_Address',
        ),
    ]
